### ISSUE TITLE
Включите github pages

### ISSUE THREAD

**Issue by jeetiss** [mediazona/data-corona-Russia#1]
Привет @merrik.
Очень круто что вы выложили данные в опенсорс!

А включите пожалуйста github pages, тогда эти данные можно будет получить по адресу `https://mediazona.github.io/data-corona-Russia/data.json` и они будут автоматически обновляться когда вы запушите новые данные

включить можно в настройках репозитория:
<img width="760" alt="Снимок экрана 2020-04-29 в 10 47 22" src="https://user-images.githubusercontent.com/6726016/80572537-1df1a000-8a07-11ea-8456-6d41bff6bd12.png">

**Comment by merrik** [comment]
Спасибо, включили!
https://mediazona.github.io/data-corona-Russia/data.json
