### ISSUE TITLE
Official data

### ISSUE THREAD

**Issue by aakhmetz** [mediazona/data-corona-Russia#3]
Hello – Thank you for your work! Would it be possible to provide a json file with official counts of confirmed cases and deaths? Then it would be possible to compare them easily.

Thank you in advance for your time,
Andrei

**Comment by ulysses4ever** [comment]
@aakhmetz [have you looked at this](https://covid19.rosminzdrav.ru/wp-json/api/mapdata/)? It's the JSON they use to populate https://covid19.rosminzdrav.ru/ -- the official Minzdrav page on COVID-19. Unfortunately, there is no daily breakout there, so I just download that file every day (you can find the copies for the previous week [in my repo](https://github.com/ulysses4ever/covid-19-in-russian-regions), in the `data` directory).

Disclaimer: I'm no Mediazona associate, I just do a similar job using the above link to update the [Wikipedia page with these numbers](https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Russia_medical_cases).

**Comment by aakhmetz** [comment]
@ulysses4ever Thank you for the link and for your work! I will probably check, but I am not sure how to use the data at the moment
